import "./globals.css";
import Navigation from './components/Navigation';
import ShareCoffee from './components/ShareCoffee';
import { Poppins } from 'next/font/google';
import Footer from "./components/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // adjust as needed
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        style={{ backgroundColor: '#212529', height: '100vh' }}
        className={`${poppins.variable} antialiased`}
      >
        <main className="font-sans">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
